### ISSUE TITLE
How to deploy NestJS server on Vercel

### ISSUE THREAD

**Issue by louyongjiu** [AmruthPillai/Reactive-Resume#1187]
I want to deploy client and server on vercel , client has been successful and the server has failed.
What can I do to do it ?

**Comment by louyongjiu** [comment]
[11:17:18.411] Cloning github.com/louyongjiu/Reactive-Resume (Branch: main, Commit: e6526cc)
[11:17:18.417] Skipping build cache since Vercel CLI used --force option
[11:17:19.111] Cloning completed: 699.52ms
[11:17:19.111] Running "npx turbo-ignore"
[11:17:20.218] npm WARN exec The following package was not found and will be installed: turbo-ignore@0.5.0
[11:17:20.427] ≫   Using Turborepo to determine if this project is affected by the commit...
[11:17:20.427] 
[11:17:20.427] ≫   `TURBO_FORCE` detected
[11:17:20.427] 
[11:17:20.427] ✅  proceeding with deployment
[11:17:20.763] Running "vercel build"
[11:17:21.242] Vercel CLI 28.11.1
[11:17:21.375] > Automatically detected Turbo monorepo manager. Attempting to assign default settings.
[11:17:21.375] WARN! Cannot automatically assign buildCommand as it is already set via project settings or configuration overrides.
[11:17:21.375] WARN! Cannot automatically assign installCommand as it is already set via project settings or configuration overrides.
[11:17:21.388] WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[11:17:21.955] Installing dependencies...
[11:17:21.955] Detected `pnpm-lock.yaml` generated by pnpm 7...
[11:17:22.499] Scope: all 4 workspace projects
[11:17:22.707] ..                                       | Progress: resolved 1, reused 0, downloaded 0, added 0
[11:17:22.990] ..                                       |    +1373 ++++++++++++++++++++++++++++
[11:17:23.468] Packages are hard linked from the content-addressable store to the virtual store.
[11:17:23.468]   Content-addressable store is at: /vercel/.local/share/pnpm/store/v3
[11:17:23.469]   Virtual store is at:             ../node_modules/.pnpm
[11:17:23.709] ..                                       | Progress: resolved 1373, reused 0, downloaded 32, added 28
[11:17:24.711] ..                                       | Progress: resolved 1373, reused 0, downloaded 94, added 89
[11:17:25.725] ..                                       | Progress: resolved 1373, reused 0, downloaded 135, added 134
[11:17:26.726] ..                                       | Progress: resolved 1373, reused 0, downloaded 151, added 149
[11:17:27.743] ..                                       | Progress: resolved 1373, reused 0, downloaded 174, added 173
[11:17:28.745] ..                                       | Progress: resolved 1373, reused 0, downloaded 199, added 198
[11:17:29.746] ..                                       | Progress: resolved 1373, reused 0, downloaded 219, added 218
[11:17:30.748] ..                                       | Progress: resolved 1373, reused 0, downloaded 261, added 259
[11:17:31.750] ..                                       | Progress: resolved 1373, reused 0, downloaded 288, added 287
[11:17:32.762] ..                                       | Progress: resolved 1373, reused 0, downloaded 347, added 341
[11:17:33.768] ..                                       | Progress: resolved 1373, reused 0, downloaded 405, added 402
[11:17:34.770] ..                                       | Progress: resolved 1373, reused 0, downloaded 448, added 446
[11:17:35.774] ..                                       | Progress: resolved 1373, reused 0, downloaded 504, added 500
[11:17:36.788] ..                                       | Progress: resolved 1373, reused 0, downloaded 569, added 566
[11:17:37.795] ..                                       | Progress: resolved 1373, reused 0, downloaded 590, added 590
[11:17:38.799] ..                                       | Progress: resolved 1373, reused 0, downloaded 622, added 621
[11:17:39.798] ..                                       | Progress: resolved 1373, reused 0, downloaded 644, added 643
[11:17:40.803] ..                                       | Progress: resolved 1373, reused 0, downloaded 684, added 684
[11:17:41.809] ..                                       | Progress: resolved 1373, reused 0, downloaded 712, added 711
[11:17:42.810] ..                                       | Progress: resolved 1373, reused 0, downloaded 770, added 771
[11:17:43.811] ..                                       | Progress: resolved 1373, reused 0, downloaded 804, added 804
[11:17:44.812] ..                                       | Progress: resolved 1373, reused 0, downloaded 827, added 827
[11:17:45.817] ..                                       | Progress: resolved 1373, reused 0, downloaded 869, added 871
[11:17:46.823] ..                                       | Progress: resolved 1373, reused 0, downloaded 884, added 883
[11:17:47.824] ..                                       | Progress: resolved 1373, reused 0, downloaded 923, added 925
[11:17:48.827] ..                                       | Progress: resolved 1373, reused 0, downloaded 952, added 954
[11:17:49.829] ..                                       | Progress: resolved 1373, reused 0, downloaded 973, added 976
[11:17:50.829] ..                                       | Progress: resolved 1373, reused 0, downloaded 987, added 990
[11:17:51.833] ..                                       | Progress: resolved 1373, reused 0, downloaded 1013, added 1017
[11:17:52.844] ..                                       | Progress: resolved 1373, reused 0, downloaded 1079, added 1081
[11:17:54.187] ..                                       | Progress: resolved 1373, reused 0, downloaded 1091, added 1093
[11:17:55.189] ..                                       | Progress: resolved 1373, reused 0, downloaded 1130, added 1129
[11:17:56.191] ..                                       | Progress: resolved 1373, reused 0, downloaded 1212, added 1214
[11:17:57.194] ..                                       | Progress: resolved 1373, reused 0, downloaded 1305, added 1307
[11:17:58.195] ..                                       | Progress: resolved 1373, reused 0, downloaded 1359, added 1362
[11:17:59.195] ..                                       | Progress: resolved 1373, reused 0, downloaded 1364, added 1369
[11:18:00.433] ..                                       | Progress: resolved 1373, reused 0, downloaded 1366, added 1371
[11:18:01.436] ..                                       | Progress: resolved 1373, reused 0, downloaded 1368, added 1373, done
[11:18:02.131] .../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[11:18:02.156] .../core-js@2.6.12/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[11:18:02.156] .../core-js@3.25.0/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[11:18:02.194] .../node_modules/@nestjs/core postinstall$ opencollective || exit 0
[11:18:02.195] .../node_modules/playwright-chromium install$ node install.js
[11:18:02.236] .../node_modules/core-js-pure postinstall: Done
[11:18:02.289] .../core-js@2.6.12/node_modules/core-js postinstall: Done
[11:18:02.413] .../core-js@3.25.0/node_modules/core-js postinstall: Done
[11:18:02.423] .../node_modules/@nestjs/core postinstall: Done
[11:18:02.597] .../node_modules/playwright-chromium install: BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
[11:18:02.597] .../node_modules/playwright-chromium install: Downloading Chromium 109.0.5414.46 (playwright build v1041) from https://playwright.azureedge.net/builds/chromium/1041/chromium-linux.zip
[11:18:02.909] .../node_modules/playwright-chromium install: |                                                                                |   0% of 140.1 Mb
[11:18:02.990] .../sharp@0.31.3/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
[11:18:03.289] .../sharp@0.31.3/node_modules/sharp install: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-linux-x64.tar.br
[11:18:03.474] .../node_modules/playwright-chromium install: |■■■■■■■■                                                                        |  10% of 140.1 Mb
[11:18:03.742] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■                                                                |  20% of 140.1 Mb
[11:18:03.928] .../sharp@0.31.3/node_modules/sharp install: sharp: Integrity check passed for linux-x64
[11:18:03.965] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 140.1 Mb
[11:18:04.149] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 140.1 Mb
[11:18:04.349] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 140.1 Mb
[11:18:04.418] .../sharp@0.31.3/node_modules/sharp install: Done
[11:18:04.507] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 140.1 Mb
[11:18:04.676] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 140.1 Mb
[11:18:04.836] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 140.1 Mb
[11:18:04.963] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 140.1 Mb
[11:18:05.082] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 140.1 Mb
[11:18:08.491] .../node_modules/playwright-chromium install: Chromium 109.0.5414.46 (playwright build v1041) downloaded to /vercel/.cache/ms-playwright/chromium-1041
[11:18:08.492] .../node_modules/playwright-chromium install: BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
[11:18:08.492] .../node_modules/playwright-chromium install: Downloading FFMPEG playwright build v1008 from https://playwright.azureedge.net/builds/ffmpeg/1008/ffmpeg-linux.zip
[11:18:08.704] .../node_modules/playwright-chromium install: |                                                                                |   0% of 2.6 Mb
[11:18:08.737] .../node_modules/playwright-chromium install: |■■■■■■■■                                                                        |  10% of 2.6 Mb
[11:18:08.759] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■                                                                |  20% of 2.6 Mb
[11:18:08.761] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 2.6 Mb
[11:18:08.772] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 2.6 Mb
[11:18:08.782] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 2.6 Mb
[11:18:08.784] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 2.6 Mb
[11:18:08.786] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 2.6 Mb
[11:18:08.794] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 2.6 Mb
[11:18:08.796] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 2.6 Mb
[11:18:08.799] .../node_modules/playwright-chromium install: |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 2.6 Mb
[11:18:08.869] .../node_modules/playwright-chromium install: FFMPEG playwright build v1008 downloaded to /vercel/.cache/ms-playwright/ffmpeg-1008
[11:18:08.876] .../node_modules/playwright-chromium install: Done
[11:18:08.898] .../.pnpm/turbo@1.6.3/node_modules/turbo postinstall$ node install.js
[11:18:08.989] .../.pnpm/turbo@1.6.3/node_modules/turbo postinstall: Done
[11:18:09.434] 
[11:18:09.434] dependencies:
[11:18:09.434] + @aws-sdk/client-s3 3.241.0
[11:18:09.434] + @nestjs/axios 1.0.1
[11:18:09.434] + @nestjs/common 9.2.1
[11:18:09.434] + @nestjs/config 2.2.0
[11:18:09.434] + @nestjs/core 9.2.1
[11:18:09.434] + @nestjs/jwt 10.0.1
[11:18:09.434] + @nestjs/mapped-types 1.2.0
[11:18:09.434] + @nestjs/passport 9.0.0
[11:18:09.434] + @nestjs/platform-express 9.2.1
[11:18:09.435] + @nestjs/schedule 2.1.0
[11:18:09.435] + @nestjs/serve-static 3.0.0
[11:18:09.435] + @nestjs/terminus 9.1.4
[11:18:09.435] + @nestjs/typeorm 9.0.1
[11:18:09.435] + @types/passport 1.0.11
[11:18:09.435] + bcryptjs 2.4.3
[11:18:09.435] + cache-manager 5.1.4
[11:18:09.435] + class-transformer 0.5.1
[11:18:09.435] + class-validator 0.13.2
[11:18:09.435] + cookie-parser 1.4.6
[11:18:09.435] + csvtojson 2.0.10
[11:18:09.435] + dayjs 1.11.7
[11:18:09.435] + google-auth-library 8.7.0
[11:18:09.435] + joi 17.7.0
[11:18:09.436] + lodash 4.17.21
[11:18:09.436] + multer 1.4.5-lts.1
[11:18:09.436] + nanoid 3.3.4
[11:18:09.436] + node-stream-zip 1.15.0
[11:18:09.436] + nodemailer 6.8.0
[11:18:09.436] + passport 0.6.0
[11:18:09.437] + passport-jwt 4.0.1
[11:18:09.437] + passport-local 1.0.0
[11:18:09.437] + pdf-lib 1.17.1
[11:18:09.437] + pg 8.8.0
[11:18:09.437] + playwright-chromium 1.29.1
[11:18:09.437] + reflect-metadata 0.1.13
[11:18:09.437] + rimraf 3.0.2
[11:18:09.438] + rxjs 7.8.0
[11:18:09.438] + typeorm 0.3.11
[11:18:09.438] + uuid 9.0.0
[11:18:09.438] 
[11:18:09.438] devDependencies:
[11:18:09.438] + @nestjs/cli 9.1.8
[11:18:09.438] + @nestjs/schematics 9.0.4
[11:18:09.438] + @reactive-resume/schema <- ../schema
[11:18:09.438] + @types/bcryptjs 2.4.2
[11:18:09.438] + @types/cookie-parser 1.4.3
[11:18:09.438] + @types/express 4.17.15
[11:18:09.438] + @types/lodash 4.14.191
[11:18:09.438] + @types/multer 1.4.7
[11:18:09.438] + @types/node 18.11.18
[11:18:09.438] + @types/nodemailer 6.4.7
[11:18:09.439] + @types/passport-jwt 3.0.8
[11:18:09.439] + @types/passport-local 1.0.34
[11:18:09.439] + @types/uuid 9.0.0
[11:18:09.439] + prettier 2.8.1
[11:18:09.439] + source-map-support 0.5.21
[11:18:09.440] + ts-loader 9.4.2
[11:18:09.440] + ts-node 10.9.1
[11:18:09.440] + tsconfig-paths 4.1.2
[11:18:09.440] + typescript 4.9.4
[11:18:09.440] + webpack 5.75.0
[11:18:09.440] 
[11:18:09.440] Done in 47.4s
[11:18:09.808] Using TypeScript 4.9.4 (local user-provided)
[11:18:13.991] [31mNowBuildError: src/filters/http-exception.filter.ts(15,14): error TS2339: Property 'status' does not exist on type 'Response<any, Record<string, any>>'.
[11:18:13.991] src/filters/http-exception.filter.ts(19,21): error TS2339: Property 'url' does not exist on type 'Request<core.ParamsDictionary, any, any, core.Query, Record<string, any>>'.
[11:18:13.991] 
[11:18:13.992]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:13.992]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:13.992]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:13.992]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:13.992]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:13.992]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:13.992]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:13.992]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:13.992]     at async Promise.all (index 9)
[11:18:13.992]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:13.992]   hideStackTrace: true,
[11:18:13.992]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:13.992]   link: undefined,
[11:18:13.993]   action: undefined
[11:18:13.993] }[0m
[11:18:14.037] [31mNowBuildError: src/integrations/integrations.module.ts(19,31): error TS2339: Property 'user' does not exist on type 'Request<core.ParamsDictionary, any, any, core.Query, Record<string, any>>'.
[11:18:14.037] 
[11:18:14.037]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:14.037]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:14.037]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:14.038]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:14.038]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:14.038]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:14.038]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:14.038]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:14.038]     at async Promise.all (index 12)
[11:18:14.038]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:14.038]   hideStackTrace: true,
[11:18:14.038]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:14.038]   link: undefined,
[11:18:14.038]   action: undefined
[11:18:14.038] }[0m
[11:18:14.250] [31mNowBuildError: src/auth/auth.service.ts(99,43): error TS2345: Argument of type '{ expiresIn: number; }' is not assignable to parameter of type 'JwtSignOptions'.
[11:18:14.250]   Object literal may only specify known properties, and 'expiresIn' does not exist in type 'JwtSignOptions'.
[11:18:14.251] 
[11:18:14.251]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:14.251]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:14.251]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:14.251]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:14.251]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:14.251]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:14.251]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:14.251]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:14.251]     at async Promise.all (index 6)
[11:18:14.251]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:14.251]   hideStackTrace: true,
[11:18:14.251]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:14.251]   link: undefined,
[11:18:14.251]   action: undefined
[11:18:14.252] }[0m
[11:18:16.587] [31mNowBuildError: src/fonts/fonts.service.ts(4,22): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:16.588] 
[11:18:16.588]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:16.588]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:16.588]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:16.588]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:16.588]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:16.588]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:16.588]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:16.589]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:16.589]     at async Promise.all (index 4)
[11:18:16.589]   hideStackTrace: true,
[11:18:16.589]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:16.589]   link: undefined,
[11:18:16.589]   action: undefined
[11:18:16.589] }[0m
[11:18:16.767] [31mNowBuildError: src/printer/printer.service.ts(4,28): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:16.767] src/printer/printer.service.ts(8,10): error TS2305: Module '"playwright-chromium"' has no exported member 'Browser'.
[11:18:16.767] src/printer/printer.service.ts(8,19): error TS2305: Module '"playwright-chromium"' has no exported member 'chromium'.
[11:18:16.767] 
[11:18:16.767]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:16.767]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:16.767]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:16.767]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:16.767]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:16.768]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:16.768]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:16.768]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:16.768]     at async Promise.all (index 3)
[11:18:16.768]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:16.768]   hideStackTrace: true,
[11:18:16.768]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:16.768]   link: undefined,
[11:18:16.768]   action: undefined
[11:18:16.768] }[0m
[11:18:16.927] [31mNowBuildError: src/resume/resume.service.ts(5,40): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:16.927] src/resume/resume.service.ts(246,27): error TS2339: Property 'send' does not exist on type 'S3Client'.
[11:18:16.927] src/resume/resume.service.ts(283,27): error TS2339: Property 'send' does not exist on type 'S3Client'.
[11:18:16.927] 
[11:18:16.927]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:16.928]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:16.928]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:16.928]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:16.928]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:16.928]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:16.928]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:16.928]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:16.928]     at async Promise.all (index 9)
[11:18:16.929]   hideStackTrace: true,
[11:18:16.929]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:16.929]   link: undefined,
[11:18:16.929]   action: undefined
[11:18:16.929] }[0m
[11:18:17.154] [31mNowBuildError: src/resume/entities/resume.entity.ts(1,43): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:17.154] 
[11:18:17.154]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:17.154]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:17.155]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:17.155]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:17.155]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:17.155]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:17.155]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:17.155]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:17.155]     at async Promise.all (index 7)
[11:18:17.155]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:17.155]   hideStackTrace: true,
[11:18:17.155]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:17.155]   link: undefined,
[11:18:17.155]   action: undefined
[11:18:17.155] }[0m
[11:18:17.455] [31mNowBuildError: src/integrations/integrations.service.ts(15,8): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:17.456] src/integrations/integrations.service.ts(260,7): error TS2740: Type 'Resume[]' is missing the following properties from type 'Resume': id, shortId, name, slug, and 7 more.
[11:18:17.456] src/integrations/integrations.service.ts(617,7): error TS2322: Type 'Resume[]' is not assignable to type 'Resume'.
[11:18:17.456] src/integrations/integrations.service.ts(949,7): error TS2322: Type 'Resume[]' is not assignable to type 'Resume'.
[11:18:17.456] 
[11:18:17.456]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:17.456]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:17.456]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:17.456]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:17.456]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:17.456]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:17.457]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:17.457]     at async Promise.all (index 7)
[11:18:17.457]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:17.457]   hideStackTrace: true,
[11:18:17.457]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:17.457]   link: undefined,
[11:18:17.457]   action: undefined
[11:18:17.457] }[0m
[11:18:18.192] [31mNowBuildError: src/resume/data/defaultState.ts(1,24): error TS2307: Cannot find module '@reactive-resume/schema' or its corresponding type declarations.
[11:18:18.192] 
[11:18:18.192]     at createTSError (/var/task/node_modules/@vercel/node/dist/index.js:300448:16)
[11:18:18.192]     at reportTSError (/var/task/node_modules/@vercel/node/dist/index.js:300454:23)
[11:18:18.192]     at getOutputTypeCheck (/var/task/node_modules/@vercel/node/dist/index.js:300554:13)
[11:18:18.192]     at compile (/var/task/node_modules/@vercel/node/dist/index.js:300630:49)
[11:18:18.192]     at compileTypeScript (/var/task/node_modules/@vercel/node/dist/index.js:299869:31)
[11:18:18.192]     at Job.readFile (/var/task/node_modules/@vercel/node/dist/index.js:299921:30)
[11:18:18.193]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227452:39)
[11:18:18.193]     at Job.maybeEmitDep (/var/task/node_modules/@vercel/node/dist/index.js:227205:17)
[11:18:18.193]     at async Promise.all (index 12)
[11:18:18.193]     at Job.emitDependency (/var/task/node_modules/@vercel/node/dist/index.js:227465:9) {
[11:18:18.193]   hideStackTrace: true,
[11:18:18.193]   code: 'NODE_TYPESCRIPT_ERROR',
[11:18:18.193]   link: undefined,
[11:18:18.193]   action: undefined
[11:18:18.193] }[0m
[11:18:30.773] Build Completed in /vercel/output [1m]
[11:18:36.757] Generated build outputs:
[11:18:36.757]  - Static files: 0
[11:18:36.757]  - Serverless Functions: 1
[11:18:36.757]  - Edge Functions: 0
[11:18:36.757] Serverless regions: Washington, D.C., USA
[11:18:36.757] Deployed outputs in 2s
[11:18:37.434] Build completed. Populating build cache...
[11:19:09.016] Uploading build cache [127.07 MB]...
[11:19:12.265] Build cache uploaded: 3.249s

**Comment by berot3** [comment]
@louyongjiu did you find anything in the meantime?

**Comment by AmruthPillai** [comment]
This issue was automatically closed as it was created before 2024-01-01.
