### ISSUE TITLE
After I deployed on centos 7, I exported pdf and got an error.Trace: Error: Navigating frame was detached

### ISSUE THREAD

**Issue by sowdf** [AmruthPillai/Reactive-Resume#1686]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

compose-chrome-1    | 2023-12-22T01:31:02.651Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: /?token=5f37202ac82b932731cece89fd314830a914300d56eb79d4d389d992c983690b: Inbound WebSocket request.
compose-chrome-1    | 2023-12-22T01:31:02.663Z browserless:hardware Checking overload status: CPU 2% Memory 15%
compose-chrome-1    | 2023-12-22T01:31:02.663Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Adding new job to queue.
compose-chrome-1    | 2023-12-22T01:31:02.663Z browserless:server Starting new job
compose-chrome-1    | 2023-12-22T01:31:02.663Z browserless:system Generating fresh chrome browser
compose-chrome-1    | 2023-12-22T01:31:02.663Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Getting browser.
compose-chrome-1    | 2023-12-22T01:31:02.664Z browserless:chrome-helper Launching Chrome with args: {
compose-chrome-1    |   "args": [
compose-chrome-1    |     "--no-sandbox",
compose-chrome-1    |     "--enable-logging",
compose-chrome-1    |     "--v1=1",
compose-chrome-1    |     "--disable-dev-shm-usage",
compose-chrome-1    |     "--no-first-run",
compose-chrome-1    |     "--remote-debugging-port=38373",
compose-chrome-1    |     "--user-data-dir=/tmp/browserless-data-dir-ZMWf39"
compose-chrome-1    |   ],
compose-chrome-1    |   "blockAds": false,
compose-chrome-1    |   "dumpio": false,
compose-chrome-1    |   "headless": "new",
compose-chrome-1    |   "stealth": false,
compose-chrome-1    |   "ignoreDefaultArgs": false,
compose-chrome-1    |   "ignoreHTTPSErrors": false,
compose-chrome-1    |   "pauseOnConnect": false,
compose-chrome-1    |   "playwright": false,
compose-chrome-1    |   "userDataDir": "/tmp/browserless-data-dir-ZMWf39",
compose-chrome-1    |   "meta": {
compose-chrome-1    |     "protocol": null,
compose-chrome-1    |     "slashes": null,
compose-chrome-1    |     "auth": null,
compose-chrome-1    |     "host": null,
compose-chrome-1    |     "port": null,
compose-chrome-1    |     "hostname": null,
compose-chrome-1    |     "hash": null,
compose-chrome-1    |     "search": "?token=5f37202ac82b932731cece89fd314830a914300d56eb79d4d389d992c983690b",
compose-chrome-1    |     "query": {
compose-chrome-1    |       "token": "5f37202ac82b932731cece89fd314830a914300d56eb79d4d389d992c983690b"
compose-chrome-1    |     },
compose-chrome-1    |     "pathname": "/",
compose-chrome-1    |     "path": "/?token=5f37202ac82b932731cece89fd314830a914300d56eb79d4d389d992c983690b",
compose-chrome-1    |     "href": "/?token=5f37202ac82b932731cece89fd314830a914300d56eb79d4d389d992c983690b"
compose-chrome-1    |   },
compose-chrome-1    |   "executablePath": "/usr/bin/google-chrome",
compose-chrome-1    |   "handleSIGINT": false,
compose-chrome-1    |   "handleSIGTERM": false,
compose-chrome-1    |   "handleSIGHUP": false
compose-chrome-1    | }
compose-chrome-1    | 2023-12-22T01:31:02.885Z browserless:chrome-helper Chrome PID: 1678
compose-chrome-1    | 2023-12-22T01:31:02.885Z browserless:chrome-helper Finding prior pages
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:chrome-helper Found 1 pages
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:chrome-helper Setting up page Unknown
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:system Chrome launched 232ms
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:system Got chrome instance
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Starting session.
compose-chrome-1    | 2023-12-22T01:31:02.895Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Proxying request to /devtools/browser route: ws://127.0.0.1:38373/devtools/browser/8dd8ca50-f293-4131-a5a1-4025d29699d0.
compose-chrome-1    | 2023-12-22T01:31:02.896Z browserless:chrome-helper Setting up file:// protocol request rejection
compose-chrome-1    | 2023-12-22T01:31:02.950Z browserless:chrome-helper Setting up page Unknown
compose-chrome-1    | 2023-12-22T01:31:02.950Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
compose-chrome-1    | 2023-12-22T01:31:02.951Z browserless:chrome-helper Setting up file:// protocol request rejection
compose-chrome-1    | 2023-12-22T01:31:12.663Z browserless:server 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Recording timedout stat.
compose-chrome-1    | 2023-12-22T01:31:12.663Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Job has timed-out, closing the WebSocket.
compose-chrome-1    | 2023-12-22T01:31:12.663Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Cleaning up job
compose-chrome-1    | 2023-12-22T01:31:12.663Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Browser not needed, closing
compose-chrome-1    | 2023-12-22T01:31:12.663Z browserless:chrome-helper Shutting down browser with close command
compose-chrome-1    | 2023-12-22T01:31:12.664Z browserless:job 7RU83MHYPK2XKPB4CH0KMX5OFDHA8HHA: Browser cleanup complete.
compose-chrome-1    | 2023-12-22T01:31:12.664Z browserless:server Current workload complete.
compose-chrome-1    | 2023-12-22T01:31:12.664Z browserless:chrome-helper Sending SIGKILL signal to browser process 1678
compose-chrome-1    | 2023-12-22T01:31:12.675Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-ZMWf39
compose-chrome-1    | 2023-12-22T01:31:12.714Z browserless:chrome-helper Garbage collecting and removing listeners
compose-chrome-1    | 2023-12-22T01:31:12.722Z browserless:chrome-helper Browser process 8dd8ca50-f293-4131-a5a1-4025d29699d0 has closed, cleaning up.
compose-chrome-1    | 2023-12-22T01:31:12.728Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-ZMWf39 removed successfully
compose-app-1       | Trace: Error: Navigating frame was detached
compose-app-1       |     at #onFrameDetached (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:109:47)
compose-app-1       |     at /app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:732
compose-app-1       |     at Array.map (<anonymous>)
compose-app-1       |     at Object.emit (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:716)
compose-app-1       |     at CdpFrame.emit (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:91:23)
compose-app-1       |     at #removeFramesRecursively (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:454:15)
compose-app-1       |     at #onClientDisconnect (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:102:42)
compose-app-1       |     at PrinterService.generateResume (/app/dist/apps/server/main.js:13239:21)
compose-app-1       |     at async /app/dist/apps/server/main.js:13133:25
compose-app-1       |     at async UtilsService.getCachedOrSet (/app/dist/apps/server/main.js:11895:23)
compose-app-1       |     at async ResumeService.printResume (/app/dist/apps/server/main.js:13978:21)
compose-app-1       |     at async ResumeController.printResume (/app/dist/apps/server/main.js:13593:25)

### Expected Behavior

download pdf 

### What template are you using?

None

**Comment by sowdf** [comment]
I use macos and there is no problem with the local development environment
