### ISSUE TITLE
[Bug] Adding an OpenAI key causes right side resume panel to freeze.

### ISSUE THREAD

**Issue by gcleaves** [AmruthPillai/Reactive-Resume#1841]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

After adding my OpenAI API key, I could no longer edit my resume properly. The right-side panel with layouts, etc. is completely frozen.

In order to unfreeze the panel, I erased all cookies and local storage and quit Chrome. This worked until I added my OpenAI AKI key again. The right side panel freezes immediately with the following error in the JS console:

```
27844.tabPrompt.js:2 TypeError: Cannot read properties of undefined (reading 'item')
    at eo (7844.tabPrompt.js:2:111370)
    at $r (7844.tabPrompt.js:2:4290647)
    at Yn (7844.tabPrompt.js:2:4299537)
    at Si (7844.tabPrompt.js:2:4338108)
    at ku (7844.tabPrompt.js:2:4329619)
    at Lu (7844.tabPrompt.js:2:4329544)
    at gu (7844.tabPrompt.js:2:4326546)
    at 7844.tabPrompt.js:2:4277925
    at t.unstable_runWithPriority (7844.tabPrompt.js:2:4447783)
    at Ko (7844.tabPrompt.js:2:4277634)
```

### Expected Behavior

The application should work as normal after entering the OpenAI API key.

### Steps To Reproduce

1. In Settings, enter your OpenAI API key.
2. Open an existing resume. 

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Chikorita

### Anything else?

<img width="411" alt="Screenshot 2024-04-01 at 14 52 22" src="https://github.com/AmruthPillai/Reactive-Resume/assets/1041253/e7c71a28-4962-44d2-b72c-6b3db7b6d4d0">

**Comment by AmruthPillai** [comment]
Ah, looks like their APIs changed over time. That's annoying as they don't have version pinning on their APIs yet. Will look into this soon.

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.
