### ISSUE TITLE
[Cant download cv pdf format] <Download PDF format>

### ISSUE THREAD

**Issue by Roua580** [AmruthPillai/Reactive-Resume#1914]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

Cant download cv pdf format when you click on the tab

### Expected Behavior

the download is supposed to launch

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

None

**Comment by vashik** [comment]
I am also observing the issue, the output is:
```
Trace: Error [TypeError]: Cannot read properties of null (reading 'cloneNode')
    at evaluate (evaluate at processPage (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13123:50), <anonymous>:1:50)
    at ExecutionContext.#evaluate (/src/github.com/AmruthPillai/Reactive-Resume/node_modules/.pnpm/puppeteer-core@22.9.0/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:431:34)
    at ExecutionContext.evaluate (/src/github.com/AmruthPillai/Reactive-Resume/node_modules/.pnpm/puppeteer-core@22.9.0/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:284:12)
    at IsolatedWorld.evaluate (/src/github.com/AmruthPillai/Reactive-Resume/node_modules/.pnpm/puppeteer-core@22.9.0/node_modules/puppeteer-core/src/cdp/IsolatedWorld.ts:192:12)
    at CdpFrame.evaluate (/src/github.com/AmruthPillai/Reactive-Resume/node_modules/.pnpm/puppeteer-core@22.9.0/node_modules/puppeteer-core/src/api/Frame.ts:470:12)
    at CdpPage.evaluate (/src/github.com/AmruthPillai/Reactive-Resume/node_modules/.pnpm/puppeteer-core@22.9.0/node_modules/puppeteer-core/src/api/Page.ts:2185:12)
    at processPage (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13123:39)
    at PrinterService.generateResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13136:17)
    at PrinterService.printResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13062:21)
    at ResumeService.printResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13859:21)
    at PrinterService.generateResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13167:21)
    at PrinterService.printResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13062:21)
    at ResumeService.printResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13859:21)
    at ResumeController.printResume (/src/github.com/AmruthPillai/Reactive-Resume/dist/apps/server/main.js:13506:25)
```

**Comment by Guo-Chenxu** [comment]
i meet this problem too, so i have to use latex to write my resume again /(ㄒoㄒ)/~~

**Comment by HUAHUAI23** [comment]
When generating PDFs, headless Chrome needs to download and import fonts from the internet. If the network environment is poor and loading times out, it can cause the PDF export to fail. I think it might be better to store the font files as static files in MinIO or on a server.

**Comment by jeremyyin2012** [comment]
I found a solution:

1. Open Sharing: toggle Public On, copy URL, open in new tab
2. Print to PDF: click Three-dot menu on top right, click Print, choose Save as PDF, Save. (Ctrl/Command + P)
3. Close Sharing: toggle Public Off !!!

PS: If we had a guide to a private preview page, it would be easy to indirectly solve this problem of exporting PDF and significantly reduce resource consumption.

**Comment by Jake-double-one** [comment]
I've fixed the problem when using a TLD like resume.example.com instead of a local hosting, only.
I'm using nginx-reverse-proxy to expose my docker container.

In the docker-compose use:
`      PUBLIC_URL: https://resume.example.com # 3002:3000
      STORAGE_URL: http://resume-download.example.com/default # 3003:9000`

In nginx you need to set up both:
resume.example.com -> server-ip:3002
resume-download.example.com -> server-ip:3003
Works both with wildcard-ssl-cert (https)

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.
