### ISSUE TITLE
Compatibility with x86-64-v1

### ISSUE THREAD

**Issue by Skorrr** [AmruthPillai/Reactive-Resume#1936]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### - Trying to run the provided simple.yml docker-compose file with the .env.example I get:

```
Minio-1 stating incompatibility with x86-64-v1
app-1 Illegal instruction (core dumped)
```

### - Trying to build the docker image I get:

```
 => ERROR [base 2/3] RUN corepack enable pnpm && corepack prepare pnpm@9.0.6 --activate                                                                                                                                                14.6s
------
 > [base 2/3] RUN corepack enable pnpm && corepack prepare pnpm@9.0.6 --activate:
3.909 Preparing pnpm@9.0.6 for immediate activation...
14.52 Internal Error: Error when performing the request to https://registry.npmjs.org/pnpm/-/pnpm-9.0.6.tgz; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
14.52     at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22762:11)
14.52     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
14.52     at async fetchUrlStream (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22792:20)
14.52     at async download (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22916:18)
14.52     at async installVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23009:55)
14.52     at async Engine.ensurePackageManager (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23452:32)
14.52     at async PrepareCommand.execute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24157:27)
14.52     at async PrepareCommand.validateAndExecute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:20954:22)
14.52     at async _Cli.run (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21929:18)
14.52     at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24230:18)
------
Dockerfile:10
--------------------
   8 |     ENV PATH="$PNPM_HOME:$PATH"
   9 |
  10 | >>> RUN corepack enable pnpm && corepack prepare pnpm@9.0.6 --activate
  11 |
  12 |     WORKDIR /app
--------------------
ERROR: failed to solve: process "/bin/sh -c corepack enable pnpm && corepack prepare pnpm@9.0.6 --activate" did not complete successfully: exit code: 1
```

### What template are you using?

None

### Anything else?

Got minio working by editing the docker-compose file to use minio:RELEASE.2024-05-28T17-19-04Z-cpuv1 build for x86-64-v1

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.
