### ISSUE TITLE
download not working 

### ISSUE THREAD

**Issue by mahmoudfakhereddin** [AmruthPillai/Reactive-Resume#1944]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

download not working 

### Expected Behavior

download working 

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

### Anything else?

download not working

**Comment by anushamhegde** [comment]
Running into same issue where its either not downloading or pdf contains only part of the resume. Tried to create a new resume with same behavior. JSON export seems to be working fine though.

**Comment by AmruthPillai** [comment]
Can someone provide some more information, any errors on the console as to what the specific error is? I keep trying to download a PDF on my account and it works every time, so it's unclear if this is a user specific issue.

**Comment by youngrichu** [comment]
> Owner

{"response":{"message":"InvalidBrowserConnection","error":"Unexpected server response: 500","statusCode":500},"status":500,"options":{},"message":"InvalidBrowserConnection","name":"InternalServerErrorException"}

**Comment by kevinjamotte** [comment]
Same here :( But thanks for your amazing work Pillai!!!!

**Comment by youngrichu** [comment]
Try it on a private( incognito window.

**Comment by kevinjamotte** [comment]
didnt work on a private window, but worked with the generated link, print to pdf option, thanks for such a quick reactivity!

**Comment by zackhanni** [comment]
Thanks @kevinjamotte the print to PDF worked for me too.

Its still not letting me do the normal export even in incognito mode, but this print webpage as PDF solution works for now.

**Comment by mtdvlpr** [comment]
Same, tried on Chrome and Firefox.

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.

**Comment by rignaneseleo** [comment]
I installed the latest version 5.0.3 and I'm unable to download pdf (tried chrome, safari and incognito).

On docker I see this in the log:
```
ORPCError: Unexpected server response: 408
    at Object.printResumeAsPDF (file:///app/.output/server/_libs/_CPjCCBv0.mjs:98101:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Object.handler (file:///app/.output/server/_libs/_CPjCCBv0.mjs:98370:17)
    at async next (file:///app/.output/server/_libs/_CPjCCBv0.mjs:29370:8)
    at async next (file:///app/.output/server/_libs/_CPjCCBv0.mjs:29365:15)
    at async file:///app/.output/server/_libs/_CPjCCBv0.mjs:29359:12
    at async next (file:///app/.output/server/_libs/_CPjCCBv0.mjs:29353:24)
    at async file:///app/.output/server/_libs/_CPjCCBv0.mjs:29281:19
    at async file:///app/.output/server/_libs/_Bw0ZhL55.mjs:3115:22
    at async file:///app/.output/server/_libs/_CPjCCBv0.mjs:28555:11 {
  defined: false,
  code: 'INTERNAL_SERVER_ERROR',
  status: 500,
  data: undefined
}
```
