### ISSUE TITLE
[Bug]  PDF generation error

### ISSUE THREAD

**Issue by knight-666** [AmruthPillai/Reactive-Resume#1969]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

Trace: InternalServerErrorException: There was an error while uploading the file.
    at StorageService.uploadObject (/app/dist/apps/server/main.js:585:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrinterService.generateResume (/app/dist/apps/server/main.js:13269:31)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13616:25) {
  response: {
    message: 'There was an error while uploading the file.',
    error: 'Internal Server Error',
    statusCode: 500
  },
  status: 500,
  options: {}
}
    at PrinterService.generateResume (/app/dist/apps/server/main.js:13276:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13616:25)
Trace: InternalServerErrorException: There was an error while uploading the file.
    at StorageService.uploadObject (/app/dist/apps/server/main.js:585:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrinterService.generateResume (/app/dist/apps/server/main.js:13269:31)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13616:25) {
  response: {
    message: 'There was an error while uploading the file.',
    error: 'Internal Server Error',
    statusCode: 500
  },
  status: 500,
  options: {}
}
    at PrinterService.generateResume (/app/dist/apps/server/main.js:13276:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13616:25)

### What template are you using?

None

**Comment by ToshY** [comment]
@knight-666 I'm having the same issue. What was your problem that cacused the exception?
