### ISSUE TITLE
[Bug] <title>Export fail

### ISSUE THREAD

**Issue by Izkraacp** [AmruthPillai/Reactive-Resume#2051]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

I try to export my resume as PDF and it just start loading then send me to a blank page and never get download I also try with the link, when and send it the link open on the same computer but also dont allow me to downloaded and when i try to open the link from a different device it never open

### Expected Behavior

I would expected to get my resume in PDF to be able to use it

### Steps To Reproduce

1 Go to export 2 PDF 3 the page just go blank
1 Copy link 2 Open the link 3 Click download 4 the page just go blank

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What template are you using?

None

### Anything else?

I am ussing the glalie templeate it is not on the list 
![blank](https://github.com/user-attachments/assets/b8fcec9b-0e9b-4d9a-a4c8-603030f54266)

**Comment by Gorcenski** [comment]
I am having the same issue, but perhaps these logs provide a hint:

```
chrome_1    |   browserless.io:server:trace  Handling inbound WebSocket request on "/?token=chrome_token" +0ms
chrome_1    |   browserless.io:server:trace  Found matching WebSocket route handler "?(/),/chromium?(/)" +6ms
chrome_1    |   browserless.io:server:trace  Authorizing WebSocket request to "http://0.0.0.0:3000/?token=chrome_token&launch=%7B%7D" +0ms
chrome_1    |   browserless.io:server:trace  Validating route query-params with QUERY schema +1ms
chrome_1    |   browserless.io:limiter:info  (Running: 0, Pending: 0) Adding to queue, max time allowed is 10,000ms  +20s
chrome_1    |   browserless.io:limiter:info  (Running: 1, Pending: 0) Starting new job  +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 Starting new ChromiumCDP instance +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 ChromiumCDP got open port 44131 +3ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 {
chrome_1    |   args: [
chrome_1    |     '--remote-debugging-port=44131',
chrome_1    |     '--no-sandbox',
chrome_1    |     '--user-data-dir=/tmp/browserless-data-dirs/browserless-data-dir-730eecda-c545-4d92-857b-e2e0d7bc1ec0'
chrome_1    |   ],
chrome_1    |   executablePath: '/usr/local/bin/playwright-browsers/chromium-1134/chrome-linux/chrome'
chrome_1    | } Launching ChromiumCDP Handler +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 ChromiumCDP is running on ws://127.0.0.1:44131/devtools/browser/315b5c52-fa41-414a-b7e4-19a96b7d6c90 +857ms
chrome_1    |   browserless.io:router:trace  Running found WebSocket handler. +21s
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 Proxying http://0.0.0.0:3000/?token=chrome_token&launch=%7B%7D to ChromiumCDP ws://127.0.0.1:44131/devtools/browser/315b5c52-fa41-414a-b7e4-19a96b7d6c90 +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 Setting up file:// protocol request rejection +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com//artboard/preview +24ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com//artboard/preview +51ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 Navigation to https://resume.emilygorcenski.com//artboard/preview +14ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/scripts/initialize-theme.js +28ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/assets/index-D_lOLxU7.js +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/assets/index-CLlCSGJ6.css +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web +2ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/scripts/initialize-theme.js +29ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/assets/index-CLlCSGJ6.css +17ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 302: https://unpkg.com/@phosphor-icons/web +31ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1 +2ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 302: https://unpkg.com/@phosphor-icons/web@2.1.1 +46ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/index.js +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/index.js +33ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css +7ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/thin/style.css +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/light/style.css +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/bold/style.css +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://unpkg.com/@phosphor-icons/web@2.1.1/src/duotone/style.css +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/thin/style.css +32ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/light/style.css +2ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/duotone/style.css +24ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/bold/style.css +2ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css +2ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css +9ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/assets/index-D_lOLxU7.js +22ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 Navigation to https://resume.emilygorcenski.com//artboard/preview +248ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/assets/ibm-plex-sans-latin-400-italic-BsicMZk3.woff2 +47ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/assets/ibm-plex-sans-latin-400-normal-CdZtFfYS.woff2 +3ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 GET: https://resume.emilygorcenski.com/icon/dark.svg +1ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/icon/dark.svg +18ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/assets/ibm-plex-sans-latin-400-italic-BsicMZk3.woff2 +12ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:trace 172.23.0.5 200: https://resume.emilygorcenski.com/assets/ibm-plex-sans-latin-400-normal-CdZtFfYS.woff2 +3ms
app_1       | Trace: Error [TypeError]: Cannot read properties of null (reading 'cloneNode')
app_1       |     at evaluate (evaluate at processPage (/app/dist/apps/server/main.js:13232:50), <anonymous>:1:50)
app_1       |     at #evaluate (/app/node_modules/.pnpm/puppeteer-core@22.10.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:376:56)
app_1       |     at async ExecutionContext.evaluate (/app/node_modules/.pnpm/puppeteer-core@22.10.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
app_1       |     at async IsolatedWorld.evaluate (/app/node_modules/.pnpm/puppeteer-core@22.10.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
app_1       |     at async CdpFrame.evaluate (/app/node_modules/.pnpm/puppeteer-core@22.10.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:342:20)
app_1       |     at async CdpPage.evaluate (/app/node_modules/.pnpm/puppeteer-core@22.10.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:823:20)
app_1       |     at async processPage (/app/dist/apps/server/main.js:13232:39)
app_1       |     at async PrinterService.generateResume (/app/dist/apps/server/main.js:13245:17)
app_1       |     at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
app_1       |     at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
app_1       |     at PrinterService.generateResume (/app/dist/apps/server/main.js:13276:21)
app_1       |     at async PrinterService.printResume (/app/dist/apps/server/main.js:13171:21)
app_1       |     at async ResumeService.printResume (/app/dist/apps/server/main.js:13969:21)
app_1       |     at async ResumeController.printResume (/app/dist/apps/server/main.js:13616:25)
chrome_1    |   browserless.io:limiter:warn  Job has hit timeout after 10,002ms of activity. +0ms
chrome_1    |   browserless.io:limiter:info  Calling timeout handler +10s
chrome_1    |   browserless.io:router:error  Websocket job has timedout, sending 429 response +0ms
chrome_1    |   browserless.io:limiter:info  (Running: 0, Pending: 0) All jobs complete.  +1ms
chrome_1    |   browserless.io:router:trace  WebSocket Request handler has finished. +9s
chrome_1    |   browserless.io:browser-manager:info  0 Client(s) are currently connected, Keep-until: 0 +0ms
chrome_1    |   browserless.io:browser-manager:info  Closing browser session +1ms
chrome_1    |   browserless.io:browser-manager:info  Deleting "/tmp/browserless-data-dirs/browserless-data-dir-730eecda-c545-4d92-857b-e2e0d7bc1ec0" user-data-dir and session from memory +0ms
chrome_1    |   browserless.io:ChromiumCDPWebSocketRoute:info 172.23.0.5 Closing ChromiumCDP process and all listeners +9s
chrome_1    |   browserless.io:server:trace  Websocket connection complete +10s
chrome_1    |   browserless.io:browser-manager:info  Deleting data directory "/tmp/browserless-data-dirs/browserless-data-dir-730eecda-c545-4d92-857b-e2e0d7bc1ec0" +7ms
```

**Comment by Gorcenski** [comment]
Ah, this is essentially the same bug as #2039 and #2040, and probably a few others.

I'm behind an nginx reverse proxy. I solved this by routing a path (I picked `/storage`) to the Minio container and setting the `STORAGE_URL` environment var:

```
# docker-compose.yaml
chrome:
  ...
  extra_hosts:
      - "host.docker.internal:host-gateway"
...
app:
  ...
      # -- URLs --
      PUBLIC_URL: <my url>
      STORAGE_URL: <my url>/storage
```

```
# nginx .conf

server {
    server_name resume.emilygorcenski.com;
    location / {
        proxy_pass http://localhost:<my app port>;
	proxy_set_header Host $http_host;
    	proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /storage {
	proxy_pass http://localhost:<my minio port>/default;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
    }
```

**Comment by karimkkanji** [comment]
Workaround as fix is being worked on: https://github.com/AmruthPillai/Reactive-Resume/issues/2058#issuecomment-2362572273

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.
