### ISSUE TITLE
[Bug] App crashes when trying to change radius on avatar

### ISSUE THREAD

**Issue by azzazkhan** [AmruthPillai/Reactive-Resume#2109]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (https://rxresu.me)

### Current Behavior

When changing radius of avatar a couple of times, the app suddenly crashes with the following error message.

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at https://rxresu.me/assets/index-D_lOLxU7.js:270:45728
    at Object.qH [as useMemo] (https://rxresu.me/assets/index-D_lOLxU7.js:38:21416)
    at Ge.useMemo (https://rxresu.me/assets/index-D_lOLxU7.js:9:6253)
    at WWt (https://rxresu.me/assets/index-D_lOLxU7.js:270:45692)
    at $E (https://rxresu.me/assets/index-D_lOLxU7.js:38:17031)
    at C7 (https://rxresu.me/assets/index-D_lOLxU7.js:40:3143)
    at C$ (https://rxresu.me/assets/index-D_lOLxU7.js:40:44880)
    at A$ (https://rxresu.me/assets/index-D_lOLxU7.js:40:39822)
    at ait (https://rxresu.me/assets/index-D_lOLxU7.js:40:39748)
    at _6 (https://rxresu.me/assets/index-D_lOLxU7.js:40:39598)
```

### Expected Behavior

The border radius of avatar should update without throwing any errors.

### Steps To Reproduce

1. Select any theme
2. Select an avatar image (I used GitHub to login so it was already included)
3. Try to change the radius of avatar (from edges to rounded and back)
4. The app will crash

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Azurill

**Comment by whoabhaysharma** [comment]
can you share the screen shots of that UI which allows to change the radius i cant see that

**Comment by azzazkhan** [comment]
Hi @whoabhaysharma, this is the popover which I used to change the border radius. I guess it's fixed now as I tried changing the radius and the app didn't crashed.

![image](https://github.com/user-attachments/assets/a5290dba-7360-447d-9d59-d3e6162b1eee)

**Comment by DemaPy** [comment]
We have 2 pull requests for such issue.
https://github.com/AmruthPillai/Reactive-Resume/pull/2119
https://github.com/AmruthPillai/Reactive-Resume/pull/1978

**Comment by amruthpillai** [comment]
Closing this issue as I'm doing some clean up to move to a newer version of the project. I apologize in advance for the inconvenience if you find the need to reopen this issue.

Please read #2499 for more information about the migration.
