### ISSUE TITLE
Error Building on Ubuntu 20.04 VPS [aka Guide on How to Build Locally]

### ISSUE THREAD

**Issue by stevethepirate88** [AmruthPillai/Reactive-Resume#397]
Currently running this on a Linode. 

the git clone works fine. When I `cd` into the repo and run `npm install` it looks like it runs fine as well.

```
npm install

> sharp@0.26.3 install /home/armedgamer/Reactive-Resume/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/armedgamer/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br

> core-js@2.6.12 postinstall /home/armedgamer/Reactive-Resume/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall /home/armedgamer/Reactive-Resume/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.8.0 postinstall /home/armedgamer/Reactive-Resume/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> protobufjs@6.10.2 postinstall /home/armedgamer/Reactive-Resume/node_modules/protobufjs
> node scripts/postinstall


> gatsby-telemetry@1.6.0 postinstall /home/armedgamer/Reactive-Resume/node_modules/gatsby-telemetry
> node src/postinstall.js || true


> mozjpeg@7.0.0 postinstall /home/armedgamer/Reactive-Resume/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@6.0.0 postinstall /home/armedgamer/Reactive-Resume/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> gatsby-cli@2.15.0 postinstall /home/armedgamer/Reactive-Resume/node_modules/gatsby/node_modules/gatsby-cli
> node scripts/postinstall.js


> gatsby@2.28.1 postinstall /home/armedgamer/Reactive-Resume/node_modules/gatsby
> node scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2944 packages from 1411 contributors and audited 2953 packages in 78.362s

218 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
I create `firebase.env` that includes only the following:

```
FIREBASE_APIKEY="$APIKEY"
FIREBASE_APPID="$APPID"
FIREBASE_AUTHDOMAIN="$AUTHDOMAIN"
FIREBASE_DATABASEURL="$DATABASEURL"
FIREBASE_MEASUREMENTID="$MEASUREMENTID"
FIREBASE_MESSAGINGSENDERID="$SENDERID"
FIREBASE_PROJECTID="$PROJECTID"
FIREBASE_STORAGEBUCKET="$STORAGEBUCKET"
```
Running `npm run start` looks like it's going well until it hits this issue:

```
info bootstrap finished - 16.159s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.918s
success write out requires - 0.059s
success run static queries - 4.125s - 4/4 0.97/s
success run page queries - 0.414s - 14/14 33.80/s
⠄ Building development bundleKilled
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! reactive-resume@2.0.0 develop: `gatsby develop`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the reactive-resume@2.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/armedgamer/.npm/_logs/2020-12-09T23_57_15_923Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! reactive-resume@2.0.0 start: `npm run develop`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the reactive-resume@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/armedgamer/.npm/_logs/2020-12-09T23_57_15_970Z-debug.log
```
Checking the logs provided I see the following:

```
cat /home/armedgamer/.npm/_logs/2020-12-09T23_57_15_923Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'develop' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle reactive-resume@2.0.0~predevelop: reactive-resume@2.0.0
6 info lifecycle reactive-resume@2.0.0~develop: reactive-resume@2.0.0
7 verbose lifecycle reactive-resume@2.0.0~develop: unsafe-perm in lifecycle true
8 verbose lifecycle reactive-resume@2.0.0~develop: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/armedgamer/Reactive-Resume/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/armedgamer/Reactive-Resume/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle reactive-resume@2.0.0~develop: CWD: /home/armedgamer/Reactive-Resume
10 silly lifecycle reactive-resume@2.0.0~develop: Args: [ '-c', 'gatsby develop' ]
11 silly lifecycle reactive-resume@2.0.0~develop: Returned: code: 137  signal: null
12 info lifecycle reactive-resume@2.0.0~develop: Failed to exec develop script
13 verbose stack Error: reactive-resume@2.0.0 develop: `gatsby develop`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid reactive-resume@2.0.0
15 verbose cwd /home/armedgamer/Reactive-Resume
16 verbose Linux 5.8.10-x86_64-linode138
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "develop"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error reactive-resume@2.0.0 develop: `gatsby develop`
22 error Exit status 137
23 error Failed at the reactive-resume@2.0.0 develop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```
The second log file:
```
cat  /home/armedgamer/.npm/_logs/2020-12-09T23_57_15_970Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactive-resume@2.0.0~prestart: reactive-resume@2.0.0
6 info lifecycle reactive-resume@2.0.0~start: reactive-resume@2.0.0
7 verbose lifecycle reactive-resume@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle reactive-resume@2.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/armedgamer/Reactive-Resume/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle reactive-resume@2.0.0~start: CWD: /home/armedgamer/Reactive-Resume
10 silly lifecycle reactive-resume@2.0.0~start: Args: [ '-c', 'npm run develop' ]
11 silly lifecycle reactive-resume@2.0.0~start: Returned: code: 137  signal: null
12 info lifecycle reactive-resume@2.0.0~start: Failed to exec start script
13 verbose stack Error: reactive-resume@2.0.0 start: `npm run develop`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid reactive-resume@2.0.0
15 verbose cwd /home/armedgamer/Reactive-Resume
16 verbose Linux 5.8.10-x86_64-linode138
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error reactive-resume@2.0.0 start: `npm run develop`
22 error Exit status 137
23 error Failed at the reactive-resume@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```
Am I missing a step here? Checking $IP:50400 I only see` Cannot GET /`

**Comment by stevethepirate88** [comment]
Alright, doing the digging, that was causing the `errno 137` was an OOM message. I need more than 1GB of RAM on the Linode. Upgraded it to 2GB, and now the issue I'm seeing is:

```
npm run start

> reactive-resume@2.0.0 start /home/armedgamer/Reactive-Resume
> npm run develop


> reactive-resume@2.0.0 develop /home/armedgamer/Reactive-Resume
> gatsby develop

success open and validate gatsby-configs - 0.130s
success load plugins - 2.830s
success onPreInit - 0.060s
success initialize cache - 0.124s
success copy gatsby files - 0.053s
success onPreBootstrap - 3.523s
success createSchemaCustomization - 0.022s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.529s
success building schema - 1.274s
info Total nodes: 89, SitePage nodes: 5 (use --verbose for breakdown)
success createPages - 0.098s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.205s
success update schema - 0.096s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.388s
success onPostBootstrap - 0.394s
info bootstrap finished - 17.861s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.997s
success write out requires - 0.070s
success run static queries - 3.909s - 4/4 1.02/s
success run page queries - 0.308s - 14/14 45.49/s
success Generating image thumbnails - 98.888s - 54/54 0.55/s
warning Critical dependency: the request of a dependency is an expression
error undefined failed

Object.entries(...).flatMap is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
error undefined failed

getProcessedPlugins is not a function
failed Building development bundle - 141.434s
error UNHANDLED REJECTION Channel closed


  Error: [ERR_IPC_CHANNEL_CLOSED]: Channel closed

  - child_process.js:636 ChildProcess.send
    internal/child_process.js:636:16

  - develop.ts:131 ControllableScript.stop
    [Reactive-Resume]/[gatsby]/src/commands/develop.ts:131:20

  - develop.ts:505 shutdownServices
    [Reactive-Resume]/[gatsby]/src/commands/develop.ts:505:28

  - develop.ts:447 process.on
    [Reactive-Resume]/[gatsby]/src/commands/develop.ts:447:11
```

**Comment by stevethepirate88** [comment]
`nvm install --lts` did the trick. Just running `sudo apt-get install npm` didn't get me what I needed on Ubuntu 20.04, had to force it is use the latest nvm.

**Comment by AmruthPillai** [comment]
Wow, this is a very detailed journey of how you got the project to start running. I hope it started working for you as expected now. And thank you for documenting the whole process as well. I'm sure it will help many others.
