### ISSUE TITLE
[BUG] ELIFECYCLE  Command failed with exit code 1.

### ISSUE THREAD

**Issue by ovizii** [AmruthPillai/Reactive-Resume#885]
**Describe the bug**
Followed these instructions and found some issues. https://raw.githubusercontent.com/AmruthPillai/Reactive-Resume/main/docker-compose.yml 
— the doc says to replace SERVER-IP – while there is no such placeholder in any of the two files
— what is the purpose of the .env when it is not referenced inside docker-compose.yml and all the variables from .env are already present in docker-compose.yml

**Product Flavor**
— [ ] Managed (https://rxresu.me)
— [X] Self Hosted

**To Reproduce**
Follow those instructions and edit the docker-compsoe.yml 

**Expected behaviour**
a working instance of reactive resume

**Desktop (please complete the following information):**
– OS:  Debian 11

**Error logs**
```
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] HealthModule dependencies initialized +1ms                           
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] MailModule dependencies initialized +1ms                             
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] JwtModule dependencies initialized +18ms                             
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] PrinterModule dependencies initialized +0ms                          
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] FontsModule dependencies initialized +1ms                            
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +82ms                     
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms                          
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms                          
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms                            
resume           | [Nest] 42  - 05/16/2022, 11:33:51 AM   ERROR [ExceptionHandler] Region is missing                                                  
resume           | Error: Region is missing                                                                                                           
resume           |     at resolveRegionConfig (/app/node_modules/.pnpm/@aws-sdk+config-resolver@3.80.0/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:9:15)                                                                                                             
resume           |     at new S3Client (/app/node_modules/.pnpm/@aws-sdk+client-s3@3.81.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:20:69) 
resume           |     at new S3 (/app/node_modules/.pnpm/@aws-sdk+client-s3@3.81.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3.js:98:1)              
resume           |     at new ResumeService (/app/server/dist/resume/resume.service.js:39:25)                                                         
resume           |     at Injector.instantiateClass (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/injector.js:330:19)                                                                                                                           
resume           |     at callback (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/injector.js:48:41)                                                                                                                                             
resume           |     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                          
resume           |     at async Injector.resolveConstructorParams (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/injector.js:122:24)                                                                                                             
resume           |     at async Injector.loadInstance (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/injector.js:52:9)                                                                                                                           
resume           |     at async Injector.loadProvider (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/injector.js:74:9)                                                                                                                           
resume           |     at async Promise.all (index 3)                                                                                                 
resume           |     at async InstanceLoader.createInstancesOfProviders (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/instance-loader.js:44:9)                                                                                                
resume           |     at async /app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/instance-loader.js:29:13                                                                                                                                           
resume           |     at async Promise.all (index 19)                                                                                                
resume           |     at async InstanceLoader.createInstances (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/instance-loader.js:28:9)                                                                                                           
resume           |     at async InstanceLoader.createInstancesOfDependencies (/app/node_modules/.pnpm/@nestjs+core@8.4.4_wy6cne2gpevj2v6pvodnemcq2i/node_modules/@nestjs/core/injector/instance-loader.js:18:9)                                                                                             
resume           | undefined                                                                                                                          
resume           | /app/server:                                                                                                                       
resume           |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @reactive-resume/server@ start:prod: `node dist/main`                                          
resume           | Exit status 1                                                                                                                      
resume           |  ELIFECYCLE  Command failed with exit code 1.          
```

**Comment by AmruthPillai** [comment]
This issue was automatically closed as it was created before 2024-01-01.
