### ISSUE TITLE
[BUG] Application error: a client-side exception has occurred after uploading a JSON from V2 and changing layout to "Leafish"

### ISSUE THREAD

**Issue by aymenkhs** [AmruthPillai/Reactive-Resume#888]
**Describe the bug**

After uploading a JSON from V2 and changing layout to "Leafish" an error occur that says 
> Application error: a client-side exception has occurred (see the browser console for more information).

**Product Flavor**
- Managed (https://rxresu.me)

**To Reproduce**

1. Upload a JSON from V2
2. Change Layout to "Leafish"
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 101.0.4951.54 (Official Build) (64-bit)

**Additional context**

Here is the content of the browser console

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bbody%2C%20heading%2C%20visible%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _a (framework-a35de9b46ea9db30.js:1:51630)
    at framework-a35de9b46ea9db30.js:1:56465
    at Uo (framework-a35de9b46ea9db30.js:1:67507)
    at Ku (framework-a35de9b46ea9db30.js:1:113539)
    at Li (framework-a35de9b46ea9db30.js:1:98957)
    at Ni (framework-a35de9b46ea9db30.js:1:98885)
    at Pi (framework-a35de9b46ea9db30.js:1:98748)
    at bi (framework-a35de9b46ea9db30.js:1:95714)
    at framework-a35de9b46ea9db30.js:1:45208
    at t.unstable_runWithPriority (framework-a35de9b46ea9db30.js:1:129353)
cu @ framework-a35de9b46ea9db30.js:1
main-f31e19238f327be1.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bbody%2C%20heading%2C%20visible%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _a (framework-a35de9b46ea9db30.js:1:51630)
    at framework-a35de9b46ea9db30.js:1:56465
    at Uo (framework-a35de9b46ea9db30.js:1:67507)
    at Ku (framework-a35de9b46ea9db30.js:1:113539)
    at Li (framework-a35de9b46ea9db30.js:1:98957)
    at Ni (framework-a35de9b46ea9db30.js:1:98885)
    at Pi (framework-a35de9b46ea9db30.js:1:98748)
    at bi (framework-a35de9b46ea9db30.js:1:95714)
    at framework-a35de9b46ea9db30.js:1:45208
    at t.unstable_runWithPriority (framework-a35de9b46ea9db30.js:1:129353)
re @ main-f31e19238f327be1.js:1
main-f31e19238f327be1.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by AmruthPillai** [comment]
This issue was automatically closed as it was created before 2024-01-01.
